"""Jira Cloud publisher — REST API v3 over plain HTTPS.

Creates one Epic per StoryForge epic and one Story per user story, with the
story linked to its parent epic and the acceptance criteria rendered in the
description (Atlassian Document Format). Idempotency is by label + summary:
re-publishing the same run does not create duplicates.

Dry-run mode builds every request body and returns it without sending — the
UI shows that as "what would be created", and the tests assert on it.
"""
from __future__ import annotations

import base64
import os
from dataclasses import dataclass, field

import httpx

from ..schemas import AnalysisResult, Story

PRIORITY_MAP = {"must": "Highest", "should": "High", "could": "Medium", "wont": "Lowest"}


class JiraError(RuntimeError):
    pass


@dataclass
class JiraConfig:
    base_url: str
    email: str
    api_token: str
    project_key: str
    epic_issue_type: str = "Epic"
    story_issue_type: str = "Story"

    @classmethod
    def from_env(cls) -> JiraConfig:
        try:
            return cls(
                base_url=os.environ["JIRA_BASE_URL"].rstrip("/"),
                email=os.environ["JIRA_EMAIL"],
                api_token=os.environ["JIRA_API_TOKEN"],
                project_key=os.environ.get("JIRA_PROJECT_KEY", "SCRUM"),
            )
        except KeyError as e:
            raise JiraError(f"missing Jira setting {e}") from e

    @property
    def configured(self) -> bool:
        return bool(self.base_url and self.email and self.api_token)


@dataclass
class PublishReport:
    dry_run: bool
    created: list[dict] = field(default_factory=list)   # {kind, id, key, url}
    skipped: list[dict] = field(default_factory=list)   # already existed
    requests: list[dict] = field(default_factory=list)  # bodies (dry run)
    errors: list[str] = field(default_factory=list)


# ----------------------------------------------------------------------------- #
# ADF helpers — Jira Cloud v3 descriptions are documents, not strings
# ----------------------------------------------------------------------------- #
def _p(text: str, marks: list[dict] | None = None) -> dict:
    node = {"type": "text", "text": text}
    if marks:
        node["marks"] = marks
    return {"type": "paragraph", "content": [node]}


def _heading(text: str, level: int = 3) -> dict:
    return {"type": "heading", "attrs": {"level": level}, "content": [{"type": "text", "text": text}]}


def _gherkin_block(story: Story) -> list[dict]:
    items = []
    for ac in story.acceptance_criteria:
        items.append(
            {
                "type": "listItem",
                "content": [
                    {
                        "type": "paragraph",
                        "content": [
                            {"type": "text", "text": "Given ", "marks": [{"type": "strong"}]},
                            {"type": "text", "text": ac.given + "\n"},
                            {"type": "text", "text": "When ", "marks": [{"type": "strong"}]},
                            {"type": "text", "text": ac.when + "\n"},
                            {"type": "text", "text": "Then ", "marks": [{"type": "strong"}]},
                            {"type": "text", "text": ac.then},
                        ],
                    }
                ],
            }
        )
    return [{"type": "orderedList", "content": items}]


def story_description(story: Story, requirement_lookup: dict[str, str]) -> dict:
    content = [_p(story.as_sentence(), [{"type": "em"}]), _heading("Acceptance criteria")]
    content += _gherkin_block(story)
    content.append(_heading("Traceability"))
    for rid in story.requirement_ids:
        content.append(_p(f"{rid}: {requirement_lookup.get(rid, '')}"))
    if story.notes:
        content += [_heading("Notes"), _p(story.notes)]
    content.append(_p("Generated by StoryForge", [{"type": "em"}]))
    return {"type": "doc", "version": 1, "content": content}


# ----------------------------------------------------------------------------- #
class JiraClient:
    def __init__(self, cfg: JiraConfig, timeout: float = 30.0):
        self.cfg = cfg
        token = base64.b64encode(f"{cfg.email}:{cfg.api_token}".encode()).decode()
        self._http = httpx.Client(
            base_url=cfg.base_url,
            timeout=timeout,
            headers={"Authorization": f"Basic {token}", "Accept": "application/json", "Content-Type": "application/json"},
        )

    # -- read -----------------------------------------------------------------
    def whoami(self) -> dict:
        r = self._http.get("/rest/api/3/myself")
        self._raise(r)
        return r.json()

    def project(self) -> dict:
        r = self._http.get(f"/rest/api/3/project/{self.cfg.project_key}")
        self._raise(r)
        return r.json()

    def issue_types(self) -> list[str]:
        return [t["name"] for t in self.project().get("issueTypes", [])]

    def search(self, jql: str, fields: str = "summary,issuetype") -> list[dict]:
        r = self._http.get("/rest/api/3/search/jql", params={"jql": jql, "fields": fields, "maxResults": 100})
        self._raise(r)
        return r.json().get("issues", [])

    def find_by_summary(self, summary: str, label: str) -> dict | None:
        safe = summary.replace('"', '\\"')
        hits = self.search(f'project = "{self.cfg.project_key}" AND labels = "{label}" AND summary ~ "\\"{safe}\\""')
        for h in hits:
            if h["fields"]["summary"] == summary:
                return h
        return None

    # -- write ----------------------------------------------------------------
    def create_issue(self, fields: dict) -> dict:
        r = self._http.post("/rest/api/3/issue", json={"fields": fields})
        self._raise(r)
        return r.json()

    def _raise(self, r: httpx.Response) -> None:
        if r.status_code >= 400:
            raise JiraError(f"Jira {r.status_code} {r.request.method} {r.request.url.path}: {r.text[:400]}")


# ----------------------------------------------------------------------------- #
def build_requests(result: AnalysisResult, cfg: JiraConfig, label: str) -> tuple[list[dict], list[dict]]:
    """Return (epic_bodies, story_bodies). Story bodies reference epics by StoryForge id;
    the publisher swaps in the real Jira key once epics exist."""
    req_lookup = {r.id: r.statement for r in result.requirements}
    epics, stories = [], []
    for e in result.backlog.epics:
        epics.append(
            {
                "_sf_id": e.id,
                "project": {"key": cfg.project_key},
                "issuetype": {"name": cfg.epic_issue_type},
                "summary": f"{e.id} {e.title}",
                "description": {"type": "doc", "version": 1, "content": [_p(e.goal), _p("Covers: " + ", ".join(e.requirement_ids))]},
                "labels": [label, "storyforge"],
            }
        )
    for s in result.backlog.stories:
        body = {
            "_sf_id": s.id,
            "_sf_epic": s.epic_id,
            "project": {"key": cfg.project_key},
            "issuetype": {"name": cfg.story_issue_type},
            "summary": f"{s.id} {s.title}",
            "description": story_description(s, req_lookup),
            "labels": [label, "storyforge", f"prio-{s.priority.value}"],
            "priority": {"name": PRIORITY_MAP[s.priority.value]},
        }
        stories.append(body)
    return epics, stories


def publish(result: AnalysisResult, cfg: JiraConfig | None = None, *, dry_run: bool = False, label: str | None = None) -> PublishReport:
    cfg = cfg or JiraConfig.from_env()
    label = label or f"sf-{result.trace.run_id}"
    epics, stories = build_requests(result, cfg, label)
    report = PublishReport(dry_run=dry_run)

    if dry_run:
        report.requests = [{k: v for k, v in b.items()} for b in epics + stories]
        return report

    client = JiraClient(cfg)
    epic_keys: dict[str, str] = {}

    for body in epics:
        sf_id = body.pop("_sf_id")
        existing = client.find_by_summary(body["summary"], label)
        if existing:
            epic_keys[sf_id] = existing["key"]
            report.skipped.append({"kind": "epic", "id": sf_id, "key": existing["key"]})
            continue
        try:
            created = client.create_issue(body)
            epic_keys[sf_id] = created["key"]
            report.created.append({"kind": "epic", "id": sf_id, "key": created["key"], "url": f"{cfg.base_url}/browse/{created['key']}"})
        except JiraError as e:
            report.errors.append(str(e))

    for body in stories:
        sf_id, sf_epic = body.pop("_sf_id"), body.pop("_sf_epic")
        if sf_epic in epic_keys:
            body["parent"] = {"key": epic_keys[sf_epic]}
        existing = client.find_by_summary(body["summary"], label)
        if existing:
            report.skipped.append({"kind": "story", "id": sf_id, "key": existing["key"]})
            continue
        try:
            created = client.create_issue(body)
            report.created.append({"kind": "story", "id": sf_id, "key": created["key"], "url": f"{cfg.base_url}/browse/{created['key']}"})
        except JiraError as e:
            # Team-managed projects sometimes reject 'priority'; retry without it once.
            if "priority" in str(e) and "priority" in body:
                body.pop("priority")
                try:
                    created = client.create_issue(body)
                    report.created.append({"kind": "story", "id": sf_id, "key": created["key"], "url": f"{cfg.base_url}/browse/{created['key']}"})
                    continue
                except JiraError as e2:
                    e = e2
            report.errors.append(str(e))
    return report
