"""Render an AnalysisResult as the documents a BA would actually circulate:
a Business Requirements Document and a backlog with a traceability matrix."""
from __future__ import annotations

from ..schemas import AnalysisResult


def _bullets(items: list[str]) -> str:
    return "\n".join(f"- {i}" for i in items) if items else "- (none stated)"


def render_brd(r: AnalysisResult) -> str:
    b = r.brief
    out = [f"# {b.title}", "", f"*Domain:* {b.domain}  ·  *Generated by StoryForge run `{r.trace.run_id}` (prompts {r.trace.prompt_version}, backend {r.trace.backend})*", ""]
    out += ["## 1. Business goals", _bullets(b.business_goals), ""]
    out += ["## 2. Stakeholders", ""]
    if b.stakeholders:
        out += ["| Name | Role | Concerns |", "|---|---|---|"]
        out += [f"| {s.name} | {s.role} | {'; '.join(s.concerns)} |" for s in b.stakeholders]
    else:
        out.append("(none identified)")
    out += ["", "## 3. Constraints", _bullets(b.constraints), ""]
    out += ["## 4. Out of scope", _bullets(b.out_of_scope), ""]
    out += ["## 5. Requirements", "", "| ID | Type | Priority | Requirement | Owner | Traceable |", "|---|---|---|---|---|---|"]
    for q in r.requirements:
        tr = "✅" if q.traceable else ("⚠️" if q.traceable is False else "–")
        out.append(f"| {q.id} | {q.type.value} | {q.priority.value.upper()} | {q.statement} | {q.stakeholder or '–'} | {tr} |")
    out += ["", "### Evidence", ""]
    for q in r.requirements:
        out.append(f"- **{q.id}** — “{q.evidence}”" + (f" *(match {q.trace_score})*" if q.traceable is False else ""))
    out += ["", "## 6. Open questions", _bullets(b.open_questions), ""]
    out += ["## 7. Gap analysis", "", r.gaps.coverage_note, ""]
    if r.gaps.gaps:
        out += ["| Severity | Kind | Gap | Ask the stakeholder |", "|---|---|---|---|"]
        out += [f"| {g.severity} | {g.kind} | {g.description} | {g.suggested_question} |" for g in r.gaps.gaps]
    out += ["", "## 8. Run summary", "",
            f"- LLM calls: {len(r.trace.calls)}  ·  tokens: {r.trace.total_tokens:,}  ·  latency: {r.trace.total_latency_ms/1000:.1f}s",
            f"- Review rounds: {r.trace.review_rounds}  ·  stories revised: {r.trace.stories_revised}",
            f"- Guardrail flags: {len(r.trace.guardrail_flags)}"]
    out += [f"  - {f}" for f in r.trace.guardrail_flags[:20]]
    return "\n".join(out) + "\n"


def render_backlog(r: AnalysisResult) -> str:
    reviews = {rv.story_id: rv for rv in r.reviews.reviews}
    out = [f"# Backlog — {r.brief.title}", ""]
    for e in r.backlog.epics:
        out += [f"## {e.id} · {e.title}", f"*Goal:* {e.goal}", ""]
        for s in [s for s in r.backlog.stories if s.epic_id == e.id]:
            rv = reviews.get(s.id)
            badge = ("✅ ready" if rv and rv.passed else "⚠️ needs work") if rv else ""
            pts = f" · {s.story_points} pts" if s.story_points else ""
            out += [f"### {s.id} · {s.title}  `{s.priority.value.upper()}`{pts}  {badge}", "", f"*{s.as_sentence()}*", "", "**Acceptance criteria**", ""]
            for i, ac in enumerate(s.acceptance_criteria, start=1):
                out += [f"{i}. **Given** {ac.given}  ", f"   **When** {ac.when}  ", f"   **Then** {ac.then}"]
            out += ["", f"*Covers:* {', '.join(s.requirement_ids)}" + (f"  ·  *revised in round {s.review_round}*" if s.review_round else "")]
            if rv:
                sc = rv.scores
                out.append(f"*INVEST:* I{sc.independent} N{sc.negotiable} V{sc.valuable} E{sc.estimable} S{sc.small} T{sc.testable}")
                if rv.issues:
                    out += ["*Open issues:*"] + [f"- {i}" for i in rv.issues]
            if s.notes:
                out.append(f"*Notes:* {s.notes}")
            out.append("")
    out += ["## Traceability matrix", "", "| Requirement | Priority | Stories | Traceable |", "|---|---|---|---|"]
    for row in r.traceability_matrix():
        out.append(f"| {row['requirement_id']} {row['statement'][:70]}{'…' if len(row['statement'])>70 else ''} | {row['priority']} | {', '.join(row['stories']) or '**none**'} | {'✅' if row['traceable'] else '⚠️'} |")
    if r.reviews.duplicate_pairs:
        out += ["", "**Possible duplicates:** " + ", ".join(f"{a}↔{b}" for a, b in r.reviews.duplicate_pairs)]
    if r.reviews.conflict_pairs:
        out += ["", "**Conflicts:** " + ", ".join(f"{a}↔{b}" for a, b in r.reviews.conflict_pairs)]
    return "\n".join(out) + "\n"


def render_csv(r: AnalysisResult) -> str:
    """Jira-importable CSV (Issue Type, Summary, Description, Priority, Labels)."""
    import csv
    import io

    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["Issue Type", "Summary", "Description", "Priority", "Labels", "Story Points", "Epic"])
    prio = {"must": "Highest", "should": "High", "could": "Medium", "wont": "Lowest"}
    epics = {e.id: e for e in r.backlog.epics}
    for e in r.backlog.epics:
        w.writerow(["Epic", f"{e.id} {e.title}", e.goal, "", "storyforge", "", ""])
    for s in r.backlog.stories:
        desc = s.as_sentence() + "\n\nAcceptance criteria:\n" + "\n\n".join(ac.as_gherkin() for ac in s.acceptance_criteria) + f"\n\nCovers: {', '.join(s.requirement_ids)}"
        w.writerow(["Story", f"{s.id} {s.title}", desc, prio[s.priority.value], "storyforge", s.story_points or "", epics.get(s.epic_id, e).title if s.epic_id in epics else ""])
    return buf.getvalue()
